### ISSUE TITLE
Warning  "No region type defined for eSc_dummyblock_c" when training a region model

### ISSUE THREAD

**Issue by fattynoparents** [stefanklut/laypa#37]
When I try training a region model, I get quite a few of such warnings:
```
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: No region type defined for eSc_dummyblock_ at /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: Element type "None" undefined in class dict /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: No region type defined for eSc_dummyblock_ at /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: Element type "None" undefined in class dict /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: No region type defined for eSc_dummyblock_ at /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
WARNING [05/06 11:19:39 laypa.page_xml.xmlPAGE]: Element type "None" undefined in class dict /home/user/training-laypa/region/2024.05.06/val_input/page/4212.xml
```

Why would this happen and should I pay attention? If yes, how can I fix this?
Thanks in advance!

**Comment by stefanklut** [comment]
This mean that in the GT there is a region that doesn't have a label. If the region has no label it will be ignored, so the pixels will just be classified (in the GT) as background

**Comment by fattynoparents** [comment]
> This mean that in the GT there is a region that doesn't have a label.

Hmm that's weird, since all regions in my GT do have labels.

**Comment by fattynoparents** [comment]
You are right, seems eScriptorium didn't remove the dummy green region that occupied the whole page (a default situation after running Loghi with only baseline detection), although I did remove it manually in their UI.
Question is, why do I get 3 similar warnings about it even though there's only 1 eSc_dummyblock_ element?

**Comment by stefanklut** [comment]
The three warning are probably due to the preprocessing reading this region 3 times (could probably be optimized :smile: ), once for semantic segmentation once for instance segmentation and once for panoptic segmentation.

This is due to the reading order, but I am not sure why this would change. Maybe @rvankoert or @TimKoornstra knows. As there were some changes to the inference script. But this is done somewhere in the Java or bash part

**Comment by fattynoparents** [comment]
> Does that mean not running the RECALCULATEREADINGORDER order as well?

This might very well be the issue, thanks for the tip, I will check this!
